all:
	mkdir ./Nfeatures/svmfeatures/models
	mkdir ./Nfeatures/svmfeatures/results
	./svm_learn -c 1 ./Nfeatures/svmfeatures/N10000_svml.dat ./Nfeatures/svmfeatures/models/N10000_svml_linear.model
	./svm_classify ./Nfeatures/svmfeatures/N10000valid_svml.dat ./Nfeatures/svmfeatures/models/N10000_svml_linear.model ./Nfeatures/svmfeatures/results/N10000_svml_linear.result
	./svm_learn -c 1 ./Nfeatures/svmfeatures/N1000_svml.dat ./Nfeatures/svmfeatures/models/N1000_svml_linear.model
	./svm_classify ./Nfeatures/svmfeatures/N1000valid_svml.dat ./Nfeatures/svmfeatures/models/N1000_svml_linear.model ./Nfeatures/svmfeatures/results/N1000_svml_linear.result
	./svm_learn -c 1 ./Nfeatures/svmfeatures/N100_svml.dat ./Nfeatures/svmfeatures/models/N100_svml_linear.model
	./svm_classify ./Nfeatures/svmfeatures/N100valid_svml.dat ./Nfeatures/svmfeatures/models/N100_svml_linear.model ./Nfeatures/svmfeatures/results/N100_svml_linear.result
	./svm_learn -c 1 ./Nfeatures/svmfeatures/N10_svml.dat ./Nfeatures/svmfeatures/models/N10_svml_linear.model
	./svm_classify ./Nfeatures/svmfeatures/N10valid_svml.dat ./Nfeatures/svmfeatures/models/N10_svml_linear.model ./Nfeatures/svmfeatures/results/N10_svml_linear.result
	./svm_learn -c 1 ./Nfeatures/svmfeatures/N12000_svml.dat ./Nfeatures/svmfeatures/models/N12000_svml_linear.model
	./svm_classify ./Nfeatures/svmfeatures/N12000valid_svml.dat ./Nfeatures/svmfeatures/models/N12000_svml_linear.model ./Nfeatures/svmfeatures/results/N12000_svml_linear.result
	./svm_learn -c 1 ./Nfeatures/svmfeatures/N14000_svml.dat ./Nfeatures/svmfeatures/models/N14000_svml_linear.model
	./svm_classify ./Nfeatures/svmfeatures/N14000valid_svml.dat ./Nfeatures/svmfeatures/models/N14000_svml_linear.model ./Nfeatures/svmfeatures/results/N14000_svml_linear.result
	./svm_learn -c 1 ./Nfeatures/svmfeatures/N16000_svml.dat ./Nfeatures/svmfeatures/models/N16000_svml_linear.model
	./svm_classify ./Nfeatures/svmfeatures/N16000valid_svml.dat ./Nfeatures/svmfeatures/models/N16000_svml_linear.model ./Nfeatures/svmfeatures/results/N16000_svml_linear.result
	./svm_learn -c 1 ./Nfeatures/svmfeatures/N18000_svml.dat ./Nfeatures/svmfeatures/models/N18000_svml_linear.model
	./svm_classify ./Nfeatures/svmfeatures/N18000valid_svml.dat ./Nfeatures/svmfeatures/models/N18000_svml_linear.model ./Nfeatures/svmfeatures/results/N18000_svml_linear.result
	./svm_learn -c 1 ./Nfeatures/svmfeatures/N1_svml.dat ./Nfeatures/svmfeatures/models/N1_svml_linear.model
	./svm_classify ./Nfeatures/svmfeatures/N1valid_svml.dat ./Nfeatures/svmfeatures/models/N1_svml_linear.model ./Nfeatures/svmfeatures/results/N1_svml_linear.result
	./svm_learn -c 1 ./Nfeatures/svmfeatures/N20000_svml.dat ./Nfeatures/svmfeatures/models/N20000_svml_linear.model
	./svm_classify ./Nfeatures/svmfeatures/N20000valid_svml.dat ./Nfeatures/svmfeatures/models/N20000_svml_linear.model ./Nfeatures/svmfeatures/results/N20000_svml_linear.result
	./svm_learn -c 1 ./Nfeatures/svmfeatures/N2000_svml.dat ./Nfeatures/svmfeatures/models/N2000_svml_linear.model
	./svm_classify ./Nfeatures/svmfeatures/N2000valid_svml.dat ./Nfeatures/svmfeatures/models/N2000_svml_linear.model ./Nfeatures/svmfeatures/results/N2000_svml_linear.result
	./svm_learn -c 1 ./Nfeatures/svmfeatures/N200_svml.dat ./Nfeatures/svmfeatures/models/N200_svml_linear.model
	./svm_classify ./Nfeatures/svmfeatures/N200valid_svml.dat ./Nfeatures/svmfeatures/models/N200_svml_linear.model ./Nfeatures/svmfeatures/results/N200_svml_linear.result
	./svm_learn -c 1 ./Nfeatures/svmfeatures/N20_svml.dat ./Nfeatures/svmfeatures/models/N20_svml_linear.model
	./svm_classify ./Nfeatures/svmfeatures/N20valid_svml.dat ./Nfeatures/svmfeatures/models/N20_svml_linear.model ./Nfeatures/svmfeatures/results/N20_svml_linear.result
	./svm_learn -c 1 ./Nfeatures/svmfeatures/N3000_svml.dat ./Nfeatures/svmfeatures/models/N3000_svml_linear.model
	./svm_classify ./Nfeatures/svmfeatures/N3000valid_svml.dat ./Nfeatures/svmfeatures/models/N3000_svml_linear.model ./Nfeatures/svmfeatures/results/N3000_svml_linear.result
	./svm_learn -c 1 ./Nfeatures/svmfeatures/N300_svml.dat ./Nfeatures/svmfeatures/models/N300_svml_linear.model
	./svm_classify ./Nfeatures/svmfeatures/N300valid_svml.dat ./Nfeatures/svmfeatures/models/N300_svml_linear.model ./Nfeatures/svmfeatures/results/N300_svml_linear.result
	./svm_learn -c 1 ./Nfeatures/svmfeatures/N4000_svml.dat ./Nfeatures/svmfeatures/models/N4000_svml_linear.model
	./svm_classify ./Nfeatures/svmfeatures/N4000valid_svml.dat ./Nfeatures/svmfeatures/models/N4000_svml_linear.model ./Nfeatures/svmfeatures/results/N4000_svml_linear.result
	./svm_learn -c 1 ./Nfeatures/svmfeatures/N400_svml.dat ./Nfeatures/svmfeatures/models/N400_svml_linear.model
	./svm_classify ./Nfeatures/svmfeatures/N400valid_svml.dat ./Nfeatures/svmfeatures/models/N400_svml_linear.model ./Nfeatures/svmfeatures/results/N400_svml_linear.result
	./svm_learn -c 1 ./Nfeatures/svmfeatures/N5000_svml.dat ./Nfeatures/svmfeatures/models/N5000_svml_linear.model
	./svm_classify ./Nfeatures/svmfeatures/N5000valid_svml.dat ./Nfeatures/svmfeatures/models/N5000_svml_linear.model ./Nfeatures/svmfeatures/results/N5000_svml_linear.result
	./svm_learn -c 1 ./Nfeatures/svmfeatures/N500_svml.dat ./Nfeatures/svmfeatures/models/N500_svml_linear.model
	./svm_classify ./Nfeatures/svmfeatures/N500valid_svml.dat ./Nfeatures/svmfeatures/models/N500_svml_linear.model ./Nfeatures/svmfeatures/results/N500_svml_linear.result
	./svm_learn -c 1 ./Nfeatures/svmfeatures/N50_svml.dat ./Nfeatures/svmfeatures/models/N50_svml_linear.model
	./svm_classify ./Nfeatures/svmfeatures/N50valid_svml.dat ./Nfeatures/svmfeatures/models/N50_svml_linear.model ./Nfeatures/svmfeatures/results/N50_svml_linear.result
	./svm_learn -c 1 ./Nfeatures/svmfeatures/N5_svml.dat ./Nfeatures/svmfeatures/models/N5_svml_linear.model
	./svm_classify ./Nfeatures/svmfeatures/N5valid_svml.dat ./Nfeatures/svmfeatures/models/N5_svml_linear.model ./Nfeatures/svmfeatures/results/N5_svml_linear.result
	./svm_learn -c 1 ./Nfeatures/svmfeatures/N6000_svml.dat ./Nfeatures/svmfeatures/models/N6000_svml_linear.model
	./svm_classify ./Nfeatures/svmfeatures/N6000valid_svml.dat ./Nfeatures/svmfeatures/models/N6000_svml_linear.model ./Nfeatures/svmfeatures/results/N6000_svml_linear.result
	./svm_learn -c 1 ./Nfeatures/svmfeatures/N600_svml.dat ./Nfeatures/svmfeatures/models/N600_svml_linear.model
	./svm_classify ./Nfeatures/svmfeatures/N600valid_svml.dat ./Nfeatures/svmfeatures/models/N600_svml_linear.model ./Nfeatures/svmfeatures/results/N600_svml_linear.result
	./svm_learn -c 1 ./Nfeatures/svmfeatures/N7000_svml.dat ./Nfeatures/svmfeatures/models/N7000_svml_linear.model
	./svm_classify ./Nfeatures/svmfeatures/N7000valid_svml.dat ./Nfeatures/svmfeatures/models/N7000_svml_linear.model ./Nfeatures/svmfeatures/results/N7000_svml_linear.result
	./svm_learn -c 1 ./Nfeatures/svmfeatures/N700_svml.dat ./Nfeatures/svmfeatures/models/N700_svml_linear.model
	./svm_classify ./Nfeatures/svmfeatures/N700valid_svml.dat ./Nfeatures/svmfeatures/models/N700_svml_linear.model ./Nfeatures/svmfeatures/results/N700_svml_linear.result
	./svm_learn -c 1 ./Nfeatures/svmfeatures/N8000_svml.dat ./Nfeatures/svmfeatures/models/N8000_svml_linear.model
	./svm_classify ./Nfeatures/svmfeatures/N8000valid_svml.dat ./Nfeatures/svmfeatures/models/N8000_svml_linear.model ./Nfeatures/svmfeatures/results/N8000_svml_linear.result
	./svm_learn -c 1 ./Nfeatures/svmfeatures/N800_svml.dat ./Nfeatures/svmfeatures/models/N800_svml_linear.model
	./svm_classify ./Nfeatures/svmfeatures/N800valid_svml.dat ./Nfeatures/svmfeatures/models/N800_svml_linear.model ./Nfeatures/svmfeatures/results/N800_svml_linear.result
	./svm_learn -c 1 ./Nfeatures/svmfeatures/N9000_svml.dat ./Nfeatures/svmfeatures/models/N9000_svml_linear.model
	./svm_classify ./Nfeatures/svmfeatures/N9000valid_svml.dat ./Nfeatures/svmfeatures/models/N9000_svml_linear.model ./Nfeatures/svmfeatures/results/N9000_svml_linear.result
	./svm_learn -c 1 ./Nfeatures/svmfeatures/N900_svml.dat ./Nfeatures/svmfeatures/models/N900_svml_linear.model
	./svm_classify ./Nfeatures/svmfeatures/N900valid_svml.dat ./Nfeatures/svmfeatures/models/N900_svml_linear.model ./Nfeatures/svmfeatures/results/N900_svml_linear.result
